### ISSUE TITLE
distanceに使用されているオブジェクトが別ライブラリのものになっている

### ISSUE THREAD

**Issue by NePonpon** [Ai-Akaishi/AiUtil#1]
修正ブランチ作成用にissueを立てます。

distance機能の中で使われているスコアボードのオブジェクトが`AiMath`となっており、これは https://github.com/Ai-Akaishi/AiMath のオブジェクトと思われます。
AiUtilでは既に、`AiUtil`というオブジェクトが作成されているため、こちらに統一する方が良いと考えています。

**Comment by Ai-Akaishi** [comment]
PullRequestありがとうございました。
